package com.mycompany.peluqueria;

import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author SuperUs
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botAna = new javax.swing.JButton();
        corteCab8 = new javax.swing.JLabel();
        corDam5 = new javax.swing.JLabel();
        tintura5 = new javax.swing.JLabel();
        peinado5 = new javax.swing.JLabel();
        botJose = new javax.swing.JButton();
        corteCab12 = new javax.swing.JLabel();
        corDam9 = new javax.swing.JLabel();
        tintura9 = new javax.swing.JLabel();
        peinado9 = new javax.swing.JLabel();
        botRoberto = new javax.swing.JButton();
        corteCab13 = new javax.swing.JLabel();
        corDam10 = new javax.swing.JLabel();
        tintura10 = new javax.swing.JLabel();
        peinado10 = new javax.swing.JLabel();
        botLucrecia = new javax.swing.JButton();
        corteCab14 = new javax.swing.JLabel();
        corDam11 = new javax.swing.JLabel();
        tintura11 = new javax.swing.JLabel();
        peinado11 = new javax.swing.JLabel();
        totales = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        reiniciar = new javax.swing.JButton();
        cortCab = new javax.swing.JTextField();
        cortDam = new javax.swing.JTextField();
        tint = new javax.swing.JTextField();
        peinado = new javax.swing.JTextField();
        cortCabb = new javax.swing.JTextField();
        cortDamm = new javax.swing.JTextField();
        tintt = new javax.swing.JTextField();
        peinadoo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        servis = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        recau = new javax.swing.JTextField();
        servis1 = new javax.swing.JTextField();
        recau1 = new javax.swing.JTextField();
        servis2 = new javax.swing.JTextField();
        recau2 = new javax.swing.JTextField();
        servis3 = new javax.swing.JTextField();
        recau3 = new javax.swing.JTextField();
        cortCab1 = new javax.swing.JTextField();
        cortDam1 = new javax.swing.JTextField();
        tint1 = new javax.swing.JTextField();
        peinado1 = new javax.swing.JTextField();
        cortCab2 = new javax.swing.JTextField();
        cortDam2 = new javax.swing.JTextField();
        tint2 = new javax.swing.JTextField();
        peinado2 = new javax.swing.JTextField();
        cortCab3 = new javax.swing.JTextField();
        cortDam3 = new javax.swing.JTextField();
        tint3 = new javax.swing.JTextField();
        peinado3 = new javax.swing.JTextField();
        cortCabb1 = new javax.swing.JTextField();
        cortDamm1 = new javax.swing.JTextField();
        tintt1 = new javax.swing.JTextField();
        peinadoo1 = new javax.swing.JTextField();
        cortCabb2 = new javax.swing.JTextField();
        cortDamm2 = new javax.swing.JTextField();
        tintt2 = new javax.swing.JTextField();
        peinadoo2 = new javax.swing.JTextField();
        cortCabb3 = new javax.swing.JTextField();
        cortDamm3 = new javax.swing.JTextField();
        tintt3 = new javax.swing.JTextField();
        peinadoo3 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        hola = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        recauT = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botAna.setText("Registrar Ana");
        botAna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botAnaActionPerformed(evt);
            }
        });
        getContentPane().add(botAna, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, -1, -1));

        corteCab8.setText("Corte caballero");
        getContentPane().add(corteCab8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 100, 30));

        corDam5.setText("Corte dama ");
        getContentPane().add(corDam5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, -1, -1));

        tintura5.setText("Tintura");
        getContentPane().add(tintura5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, -1, -1));

        peinado5.setText("Peinado");
        getContentPane().add(peinado5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, -1, -1));

        botJose.setText("Registrar Jose");
        botJose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botJoseActionPerformed(evt);
            }
        });
        getContentPane().add(botJose, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 100, -1, -1));

        corteCab12.setText("Corte caballero");
        getContentPane().add(corteCab12, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 130, 100, 30));

        corDam9.setText("Corte dama ");
        getContentPane().add(corDam9, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 160, -1, -1));

        tintura9.setText("Tintura");
        getContentPane().add(tintura9, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 190, -1, -1));

        peinado9.setText("Peinado");
        getContentPane().add(peinado9, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 220, -1, -1));

        botRoberto.setText("Registrar Roberto");
        botRoberto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botRobertoActionPerformed(evt);
            }
        });
        getContentPane().add(botRoberto, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, -1, -1));

        corteCab13.setText("Corte caballero");
        getContentPane().add(corteCab13, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 100, 30));

        corDam10.setText("Corte dama ");
        getContentPane().add(corDam10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, -1, -1));

        tintura10.setText("Tintura");
        getContentPane().add(tintura10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 420, -1, -1));

        peinado10.setText("Peinado");
        getContentPane().add(peinado10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 450, -1, -1));

        botLucrecia.setText("Registrar Lucrecia");
        botLucrecia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botLucreciaActionPerformed(evt);
            }
        });
        getContentPane().add(botLucrecia, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 330, -1, -1));

        corteCab14.setText("Corte caballero");
        getContentPane().add(corteCab14, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 360, 100, 30));

        corDam11.setText("Corte dama ");
        getContentPane().add(corDam11, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 390, -1, -1));

        tintura11.setText("Tintura");
        getContentPane().add(tintura11, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 420, -1, -1));

        peinado11.setText("Peinado");
        getContentPane().add(peinado11, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 450, -1, -1));

        totales.setText("VER TOTALES");
        totales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalesActionPerformed(evt);
            }
        });
        getContentPane().add(totales, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 630, -1, -1));

        jButton2.setText("SALIR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 630, -1, -1));

        reiniciar.setText("INICIAR DIA ");
        reiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reiniciarActionPerformed(evt);
            }
        });
        getContentPane().add(reiniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 630, -1, -1));

        cortCab.setEditable(false);
        cortCab.setText("0");
        cortCab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cortCabActionPerformed(evt);
            }
        });
        getContentPane().add(cortCab, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 50, -1));

        cortDam.setEditable(false);
        cortDam.setText("0");
        cortDam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cortDamActionPerformed(evt);
            }
        });
        getContentPane().add(cortDam, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 50, -1));

        tint.setEditable(false);
        tint.setText("0");
        getContentPane().add(tint, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 50, -1));

        peinado.setEditable(false);
        peinado.setText("0");
        peinado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peinadoActionPerformed(evt);
            }
        });
        getContentPane().add(peinado, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 50, -1));

        cortCabb.setText("0");
        getContentPane().add(cortCabb, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 40, -1));

        cortDamm.setText("0");
        getContentPane().add(cortDamm, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 40, -1));

        tintt.setText("0");
        getContentPane().add(tintt, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 40, -1));

        peinadoo.setText("0");
        getContentPane().add(peinadoo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 40, -1));

        jLabel1.setText("Total  servicios");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, -1, -1));

        jLabel5.setText("Total  recaudos");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, -1, -1));

        jLabel2.setText("Total  servicios");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, -1, -1));

        jLabel6.setText("Total  recaudos");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 280, -1, -1));

        jLabel3.setText("Total  servicios");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 480, -1, -1));

        jLabel7.setText("Total  recaudos");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 510, -1, -1));

        jLabel4.setText("Total  servicios");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 480, -1, -1));

        servis.setEditable(false);
        servis.setText("0");
        getContentPane().add(servis, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 480, 80, -1));

        jLabel8.setText("Total  recaudos");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 510, -1, -1));

        recau.setEditable(false);
        recau.setText("0");
        getContentPane().add(recau, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 510, 80, -1));

        servis1.setEditable(false);
        servis1.setText("0");
        getContentPane().add(servis1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 480, 80, -1));

        recau1.setEditable(false);
        recau1.setText("0");
        getContentPane().add(recau1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 510, 80, -1));

        servis2.setEditable(false);
        servis2.setText("0");
        servis2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                servis2ActionPerformed(evt);
            }
        });
        getContentPane().add(servis2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 80, -1));

        recau2.setEditable(false);
        recau2.setText("0");
        getContentPane().add(recau2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 80, -1));

        servis3.setEditable(false);
        servis3.setText("0");
        servis3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                servis3ActionPerformed(evt);
            }
        });
        getContentPane().add(servis3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 250, 80, -1));

        recau3.setEditable(false);
        recau3.setText("0");
        getContentPane().add(recau3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 280, 80, -1));

        cortCab1.setEditable(false);
        cortCab1.setText("0");
        cortCab1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cortCab1ActionPerformed(evt);
            }
        });
        getContentPane().add(cortCab1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 130, 50, -1));

        cortDam1.setEditable(false);
        cortDam1.setText("0");
        getContentPane().add(cortDam1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 160, 50, -1));

        tint1.setEditable(false);
        tint1.setText("0");
        tint1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tint1ActionPerformed(evt);
            }
        });
        getContentPane().add(tint1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 190, 50, -1));

        peinado1.setEditable(false);
        peinado1.setText("0");
        peinado1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peinado1ActionPerformed(evt);
            }
        });
        getContentPane().add(peinado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 220, 50, -1));

        cortCab2.setEditable(false);
        cortCab2.setText("0");
        getContentPane().add(cortCab2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, 50, -1));

        cortDam2.setEditable(false);
        cortDam2.setText("0");
        getContentPane().add(cortDam2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 390, 50, -1));

        tint2.setEditable(false);
        tint2.setText("0");
        getContentPane().add(tint2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 420, 50, -1));

        peinado2.setEditable(false);
        peinado2.setText("0");
        getContentPane().add(peinado2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 450, 50, -1));

        cortCab3.setEditable(false);
        cortCab3.setText("0");
        getContentPane().add(cortCab3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 360, 50, -1));

        cortDam3.setEditable(false);
        cortDam3.setText("0");
        getContentPane().add(cortDam3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 390, 50, -1));

        tint3.setEditable(false);
        tint3.setText("0");
        getContentPane().add(tint3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 420, 50, -1));

        peinado3.setEditable(false);
        peinado3.setText("0");
        getContentPane().add(peinado3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 450, 50, -1));

        cortCabb1.setText("0");
        getContentPane().add(cortCabb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 130, 40, -1));

        cortDamm1.setText("0");
        getContentPane().add(cortDamm1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 160, 40, -1));

        tintt1.setText("0");
        getContentPane().add(tintt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 190, 40, -1));

        peinadoo1.setText("0");
        getContentPane().add(peinadoo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 220, 40, -1));

        cortCabb2.setText("0");
        getContentPane().add(cortCabb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, 40, -1));

        cortDamm2.setText("0");
        getContentPane().add(cortDamm2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, 40, -1));

        tintt2.setText("0");
        tintt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tintt2ActionPerformed(evt);
            }
        });
        getContentPane().add(tintt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 420, 40, -1));

        peinadoo2.setText("0");
        getContentPane().add(peinadoo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 450, 40, -1));

        cortCabb3.setText("0");
        getContentPane().add(cortCabb3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 360, 40, -1));

        cortDamm3.setText("0");
        getContentPane().add(cortDamm3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 390, 40, -1));

        tintt3.setText("0");
        getContentPane().add(tintt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 420, 40, -1));

        peinadoo3.setText("0");
        getContentPane().add(peinadoo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 450, 40, -1));

        jLabel9.setFont(new java.awt.Font("Stencil", 1, 36)); // NOI18N
        jLabel9.setText("PELUQUERIA UNIVERSIDAD DE CUNDINAMARCA");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, -1, -1));

        hola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                holaActionPerformed(evt);
            }
        });
        getContentPane().add(hola, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 550, 80, -1));

        jLabel10.setText("servicios totales");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 560, -1, -1));

        jLabel11.setText("recaudos totales");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 590, -1, -1));
        getContentPane().add(recauT, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 590, 80, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botAnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botAnaActionPerformed
        Ana Ana = new Ana();
        Ana.setcortCabb(Integer.parseInt(cortCabb.getText()));
        Ana.setcortDamm(Integer.parseInt(cortDamm.getText()));
        Ana.settintt(Integer.parseInt(tintt.getText()));
        Ana.setpeinadoo(Integer.parseInt(peinadoo.getText()));
        cortCab.setText("$" + Integer.toString(Ana.cortCab));
        cortDam.setText("$" + Integer.toString(Ana.cortDam));
        tint.setText("$" + Integer.toString(Ana.tint));
        peinado.setText("$" + Integer.toString(Ana.peinado));
        servis2.setText("$" + Integer.toString(Ana.getServis2()));
        recau2.setText("$" + Integer.toString(Ana.getRecau2()));

    }//GEN-LAST:event_botAnaActionPerformed

    private void botJoseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botJoseActionPerformed
        Jose Jose = new Jose();
        Jose.setcortCabb1(Integer.parseInt(cortCabb1.getText()));
        Jose.setcortDamm1(Integer.parseInt(cortDamm1.getText()));
        Jose.settintt1(Integer.parseInt(tintt1.getText()));
        Jose.setpeinadoo1(Integer.parseInt(peinadoo1.getText()));
        cortCab1.setText("$" + Integer.toString(Jose.cortCab));
        cortDam1.setText("$" + Integer.toString(Jose.cortDam));
        tint1.setText("$" + Integer.toString(Jose.tint));
        peinado1.setText("$" + Integer.toString(Jose.peinado));
        servis3.setText("$" + Integer.toString(Jose.getServis3()));
        recau3.setText("$" + Integer.toString(Jose.getRecau3()));


    }//GEN-LAST:event_botJoseActionPerformed

    private void botRobertoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botRobertoActionPerformed
        Roberto Roberto = new Roberto();
        Roberto.setcortCabb2(Integer.parseInt(cortCabb2.getText()));
        Roberto.setcortDamm2(Integer.parseInt(cortDamm2.getText()));
        Roberto.settintt2(Integer.parseInt(tintt2.getText()));
        Roberto.setpeinadoo2(Integer.parseInt(peinadoo2.getText()));
        cortCab2.setText("$" + Integer.toString(Roberto.cortCab));
        cortDam2.setText("$" + Integer.toString(Roberto.cortDam));
        tint2.setText("$" + Integer.toString(Roberto.tint));
        peinado2.setText("$" + Integer.toString(Roberto.peinado));
        servis1.setText("$" + Integer.toString(Roberto.getServis1()));
        recau1.setText("$" + Integer.toString(Roberto.getRecau1()));


    }//GEN-LAST:event_botRobertoActionPerformed

    private void botLucreciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botLucreciaActionPerformed
        Lucrecia Lucrecia = new Lucrecia();
        Lucrecia.setcortCabb3(Integer.parseInt(cortCabb3.getText()));
        Lucrecia.setcortDamm3(Integer.parseInt(cortDamm3.getText()));
        Lucrecia.settintt3(Integer.parseInt(tintt3.getText()));
        Lucrecia.setpeinadoo3(Integer.parseInt(peinadoo3.getText()));
        cortCab3.setText("$" + Integer.toString(Lucrecia.cortCab));
        cortDam3.setText("$" + Integer.toString(Lucrecia.cortDam));
        tint3.setText("$" + Integer.toString(Lucrecia.tint));
        peinado3.setText("$" + Integer.toString(Lucrecia.peinado));
        servis.setText("$" + Integer.toString(Lucrecia.getServis()));
        recau.setText("$" + Integer.toString(Lucrecia.getRecau()));


    }//GEN-LAST:event_botLucreciaActionPerformed

    private void totalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalesActionPerformed

        
        double numero1 = Double.parseDouble(servis.getText());
        double numero2 = Double.parseDouble(servis1.getText());
        double numero3 = Double.parseDouble(servis2.getText());
        double numero4 = Double.parseDouble(servis3.getText());
        double numero5 = Double.parseDouble(recau.getText());
        double numero6 = Double.parseDouble(recau1.getText());
        double numero7 = Double.parseDouble(recau2.getText());
        double numero8 = Double.parseDouble(recau3.getText());
        
        
        double total= numero1+numero2+numero3+numero4;
        double total1= numero5+numero6+numero7+numero8;
        hola.setText(String.valueOf(total));
        recauT.setText(String.valueOf(total1));
        
        //JOptionPane.showMessageDialog(this, "La suma es: " + total, "Resultado", JOptionPane.INFORMATION_MESSAGE);
        
        
        
       


    }//GEN-LAST:event_totalesActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cortCab1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cortCab1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cortCab1ActionPerformed

    private void tint1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tint1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tint1ActionPerformed

    private void peinado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peinado1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_peinado1ActionPerformed

    private void cortDamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cortDamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cortDamActionPerformed

    private void peinadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peinadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_peinadoActionPerformed

    private void servis2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_servis2ActionPerformed
     
    }//GEN-LAST:event_servis2ActionPerformed

    private void cortCabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cortCabActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cortCabActionPerformed

    private void reiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reiniciarActionPerformed
        cortCabb.setText(Integer.toString(0));
        cortDamm.setText(Integer.toString(0));
        tintt.setText(Integer.toString(0));
        peinadoo.setText(Integer.toString(0));
        cortCab.setText(Integer.toString(0));
        cortDam.setText(Integer.toString(0));
        tint.setText(Integer.toString(0));
        peinado.setText(Integer.toString(0));
        servis.setText(Integer.toString(0));
        recau.setText(Integer.toString(0));

        cortCabb1.setText(Integer.toString(0));
        cortDamm1.setText(Integer.toString(0));
        tintt1.setText(Integer.toString(0));
        peinadoo1.setText(Integer.toString(0));
        cortCab1.setText(Integer.toString(0));
        cortDam1.setText(Integer.toString(0));
        tint1.setText(Integer.toString(0));
        peinado1.setText(Integer.toString(0));
        servis1.setText(Integer.toString(0));
        recau1.setText(Integer.toString(0));

        cortCabb2.setText(Integer.toString(0));
        cortDamm2.setText(Integer.toString(0));
        tintt2.setText(Integer.toString(0));
        peinadoo2.setText(Integer.toString(0));
        cortCab2.setText(Integer.toString(0));
        cortDam2.setText(Integer.toString(0));
        tint2.setText(Integer.toString(0));
        peinado2.setText(Integer.toString(0));
        servis2.setText(Integer.toString(0));
        recau2.setText(Integer.toString(0));

        cortCabb3.setText(Integer.toString(0));
        cortDamm3.setText(Integer.toString(0));
        tintt3.setText(Integer.toString(0));
        peinadoo3.setText(Integer.toString(0));
        cortCab3.setText(Integer.toString(0));
        cortDam3.setText(Integer.toString(0));
        tint3.setText(Integer.toString(0));
        peinado3.setText(Integer.toString(0));
        servis3.setText(Integer.toString(0));
        recau3.setText(Integer.toString(0));


    }//GEN-LAST:event_reiniciarActionPerformed

    private void tintt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tintt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tintt2ActionPerformed

    private void servis3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_servis3ActionPerformed
      
    }//GEN-LAST:event_servis3ActionPerformed

    private void holaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_holaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_holaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botAna;
    private javax.swing.JButton botJose;
    private javax.swing.JButton botLucrecia;
    private javax.swing.JButton botRoberto;
    private javax.swing.JLabel corDam10;
    private javax.swing.JLabel corDam11;
    private javax.swing.JLabel corDam5;
    private javax.swing.JLabel corDam9;
    private javax.swing.JTextField cortCab;
    private javax.swing.JTextField cortCab1;
    private javax.swing.JTextField cortCab2;
    private javax.swing.JTextField cortCab3;
    private javax.swing.JTextField cortCabb;
    private javax.swing.JTextField cortCabb1;
    private javax.swing.JTextField cortCabb2;
    private javax.swing.JTextField cortCabb3;
    private javax.swing.JTextField cortDam;
    private javax.swing.JTextField cortDam1;
    private javax.swing.JTextField cortDam2;
    private javax.swing.JTextField cortDam3;
    private javax.swing.JTextField cortDamm;
    private javax.swing.JTextField cortDamm1;
    private javax.swing.JTextField cortDamm2;
    private javax.swing.JTextField cortDamm3;
    private javax.swing.JLabel corteCab12;
    private javax.swing.JLabel corteCab13;
    private javax.swing.JLabel corteCab14;
    private javax.swing.JLabel corteCab8;
    private javax.swing.JTextField hola;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField peinado;
    private javax.swing.JTextField peinado1;
    private javax.swing.JLabel peinado10;
    private javax.swing.JLabel peinado11;
    private javax.swing.JTextField peinado2;
    private javax.swing.JTextField peinado3;
    private javax.swing.JLabel peinado5;
    private javax.swing.JLabel peinado9;
    private javax.swing.JTextField peinadoo;
    private javax.swing.JTextField peinadoo1;
    private javax.swing.JTextField peinadoo2;
    private javax.swing.JTextField peinadoo3;
    private javax.swing.JTextField recau;
    private javax.swing.JTextField recau1;
    private javax.swing.JTextField recau2;
    private javax.swing.JTextField recau3;
    private javax.swing.JTextField recauT;
    private javax.swing.JButton reiniciar;
    private javax.swing.JTextField servis;
    private javax.swing.JTextField servis1;
    private javax.swing.JTextField servis2;
    private javax.swing.JTextField servis3;
    private javax.swing.JTextField tint;
    private javax.swing.JTextField tint1;
    private javax.swing.JTextField tint2;
    private javax.swing.JTextField tint3;
    private javax.swing.JTextField tintt;
    private javax.swing.JTextField tintt1;
    private javax.swing.JTextField tintt2;
    private javax.swing.JTextField tintt3;
    private javax.swing.JLabel tintura10;
    private javax.swing.JLabel tintura11;
    private javax.swing.JLabel tintura5;
    private javax.swing.JLabel tintura9;
    private javax.swing.JButton totales;
    // End of variables declaration//GEN-END:variables
}
